- .gitignore
- example/main.go
- go-pinot-api.go
- model/GetUsersReponse.go
- model/User.go
- refactors code
- needed to be refactored
> Refactors client along with example

- go-pinot-api.go
CreateUserResponse was changed to model.UserActionResponse in the #3
> fixing mismatched response types

- go-pinot-api.go
Adding functionality to delete a schema by name
> Adds DeleteSchema functionality

- example/main.go
- matches table config example to the schema example
- shifts it below schema so it is created correctly
> updated examples with table CRUD

- example/main.go
- Moved getSchema function above main in examples
> moved getSchema function

- config/broker.conf
- config/controller.conf
- docker-compose.yaml
- example/main.go
- Adds controller.conf to the config folder
- updates the docker-compose file
> updated docker compose to add auth to controller

- example/main.go
- go-pinot-api.go
- update fetchData to use encode
- implements generateQueryMap
> fixing fetchData url issue

- example/main.go
- go-pinot-api.go
- model/GetSegmentMetadataResponse.go
- model/GetSegmentsResponse.go
- model/Segment.go
- Adds functionality to reload segments for all tables
- Adds functionality to reload segments for a given table
> 17 add segment management functionality

- example/main.go
- go-pinot-api.go
> uncommenting getSegments

- config-templating/templater.go
- config-templating/templater_test.go
Some more functionality for rending table templates
> Adding More Templating Functionality

- example/main.go
- go-pinot-api.go
- model/ClusterConfig.go
- model/GetClusterConfigResponse.go
- model/GetClusterResponse.go
- Implements Get ClusterName, Get ClusterConfigInfo, Update ClusterConfig and Delete ClusterConfig
> adding cluster functionality

- example/main.go
- go-pinot-api.go
- model/GetTenantMetadataResponse.go
- model/GetTenantResponse.go
- model/Tenant.go
- Adds:
- GetTenants
- GetTenantInstances
- GetTenantTables
- GetTenantMetadata
- CreateTenant
- UpdateTenant
- DeleteTenant
- RebalanceTenant
- Fixes DeleteObject URL encoding
> Added tenant functionality, fixed Delete url encoding

- .github/workflows/coverage.yaml
> fixed bug in coverage action

- README.md
- updates badge style to for the badge
> updated badge style

- go-pinot-api.go
- Adds the prepareRequestURL, moving it out of fetchData and DeleteObject functions
> added prepareRequestURL

- example/main.go
- go-pinot-api.go
- model/GetInstanceResponse.go
- model/GetInstancesResponse.go
- model/Instance.go
- Add CRUD for Instances
- Adds demo for Instances to examples
> added CRUD for Instances, and added the demo to examples

- go-pinot-api.go
Adds better message  to failed http response error
> Adds better error message logging

- integration-test/container/pinot.go
- integration-test/go.mod
- integration-test/go.sum
- updates integration tests to v0.1.4
> updated go-pinot-api version in integration tests

- .github/workflows/unit-test.yaml
- example/main.go
- go-pinot-api.go
- go-pinot-api_test.go
- go.mod
- go.sum
- Fixes issue in deleteobject url query
- adds go-pinot-api_test.go
- Implements some user unit tests
- adds a unit test automation step for go-pinot-api
> 85 implement unit testing   user

- README.md
- adds codacy test coverage badge
> adding codacy coverage badge

- go-pinot-api_test.go
> added cluster unit tests

- config-templating/templater_test.go
- model/Table.go
Forgot to make struct fields pointers so that `omitempty` works
> Makes some fields pointers so `omitempty` works

- go-pinot-api_test.go
> added tenant unit tests

- go-pinot-api_test.go
- Adds unit tests for segments
> added segment unit tests

- example/main.go
- go-pinot-api.go
- model/CreateSchemaResponse.go
- Adds CreateSchemaFromBytes function which follows the pattern of the other functions, still includes validation
- Updates CreateObject to handle the case where the POST url has queries
- Implements CreateSchemaResponse to unmarshall status and unrecognizedProperties from the create response
> adds CreateSchemaFromBytes to match pattern of other features, unmarshalls status

- example/main.go
- go-pinot-api.go
- go-pinot-api_test.go
- Implements UpdateSchemaFromBytes, this matches the pattern of the other functions for other resources
- Implements UnitTests for Schemas
> 106 implement unit testing   schema

- go-pinot-api_test.go
- model/Table.go
- implements IsEmpty for tables
> added IsEmpty for tables

- model/Table.go
Adding some additional fields that were missing from `UpsertConfig`
> Adds additional fields for `UpsertConfig`

- model/Table.go
Adding `filterConfig` to `ingestionConfig`
> Adds `filterConfig` to ingestion config

- tools/coverage/coverage.go
- Adds a map for tracking coverage status
> added coveragemap to track uncovered paths

- example/main.go
- go-pinot-api.go
- go-pinot-api_test.go
- model/PlainTextAPIResponse.go
- added plaintextresponse
- added health checks
- added unit tests
> added plaintextresponse, added health checks, +unit tests

- example/main.go
- go-pinot-api.go
- go-pinot-api_test.go
- model/GetSchemaFieldSpecsResponse.go
- added getschemafieldspec
- adds unit tests
> added getschemafieldspec + unit tests

- example/main.go
- go-pinot-api.go
- go-pinot-api_test.go
- model/GetSegmentCRCResponse.go
- model/GetSegmentMetadataResponse.go
- model/GetSegmentTiersResponse.go
- model/GetSegmentZKMetadataResponse.go
adds:
- resetTableSegment
- resetTableSegments
- getSegementTiers
- getSegmentCRC
- getSegmentMetadata
- getSegmentZKMetadata
+ unit tests
> 142 improve api coverage   segments

- model/Table.go
Adding `task` section for table config
https://docs.pinot.apache.org/basics/concepts/components/cluster/minion#enable-tasks
> Adds `Task` config section for table configs

- example/main.go
- go-pinot-api.go
- go-pinot-api_test.go
- model/User.go
- adds permissions and tables as optional string slices for user struct
- adds unit tests
> added permissions and tables as optional fields in user struct

- model/Table.go
Updates keys to match pinot documentation
> Updates Tasks config

- model/Table.go
Adding required schema name to segmentsConfig object for Realtime table creation
> Add SchemaName on TableSegmentsConfig struct

- model/Table.go
> Fixes `enablePreload`

- model/Table.go
Hello @azaurus1
We would like to add some features that @JoaoRigonNeto and I implemented:
- Map TagOverrideConfig on TableTenant struct
- Map InstanceAssignmentConfigMap on Table struct
I will also implement it in the terraform-provider-pinot project.
> Add TagOverrideConfig on TableTenant struct and InstanceAssignmentConfigMap on Table struct

- model/Table.go
Hello @azaurus1
We would like to add some features that @JoaoRigonNeto and I implemented:
- Change MinimizeDataMovement, PoolBased and ReplicaGroupBased to pointer value.
- Create struct function for validate if object is null
I will also implement it in the terraform-provider-pinot project.
> Change bool properties for bool pointer. Create IsEmpty some struct to validate if object is empty

- model/Table.go
adding new indexing fields that are listed in https://docs.pinot.apache.org/basics/indexing
also fixing typo in `FiendIndexInverted`
> feat(table): add missing field indexes
